### PR TITLE
Custom build step support

### PR DESCRIPTION
**Pull request by mmicko**
Added support for executing custom build steps for gmake and Visual Studio, and ability do define dependencies between files.

Also added postcompiletasks task that will be executed after compiling each file in gmake files

few examples : 

dependency format is: source file , depending file
dependency {
	{ MAME_DIR .. "src/emu/cpu/m6809/m6809.c",   GEN_DIR .. "emu/cpu/m6809/m6809.inc" },
	{ MAME_DIR .. "src/emu/cpu/m6809/hd6309.c",  GEN_DIR .. "emu/cpu/m6809/hd6309.inc" },
	{ MAME_DIR .. "src/emu/cpu/m6809/konami.c",  GEN_DIR .. "emu/cpu/m6809/konami.inc" },
}	

custombuildtask is in format : source file, generated file, list of dependencies for building, list of commands to be executed
note that parameters in commands are replaced : __I__ is input file (source file), __O__ is output file (generated file), and those from list of dependencies are __1__, __2__ and so on
needed output folders are generated automatically

custombuildtask {
	{ MAME_DIR .. "src/emu/cpu/m6809/m6809.ops"  , GEN_DIR .. "emu/cpu/m6809/m6809.inc",   { MAME_DIR .. "src/emu/cpu/m6809/m6809make.py"  , MAME_DIR .. "src/emu/cpu/m6809/base6x09.ops"  }, {"@echo Generating m6809 source file...", "python __1__ __I__ > __O__" }},
	{ MAME_DIR .. "src/emu/cpu/m6809/hd6309.ops" , GEN_DIR .. "emu/cpu/m6809/hd6309.inc",  { MAME_DIR .. "src/emu/cpu/m6809/m6809make.py"  , MAME_DIR .. "src/emu/cpu/m6809/base6x09.ops"  }, {"@echo Generating hd6309 source file...", "python __1__ __I__ > __O__" }},
	{ MAME_DIR .. "src/emu/cpu/m6809/konami.ops" , GEN_DIR .. "emu/cpu/m6809/konami.inc",  { MAME_DIR .. "src/emu/cpu/m6809/m6809make.py"  , MAME_DIR .. "src/emu/cpu/m6809/base6x09.ops"  }, {"@echo Generating konami source file...", "python __1__ __I__ > __O__" }},
}	

postcompiletasks is gmake specific and contain list of commands that will be executed after each compiled file

postcompiletasks { 
	"gawk -f ../../../../../scripts/depfilter.awk $(@:%.o=%.d) > $(@:%.o=%.dep)", 
	"mv $(@:%.o=%.dep) $(@:%.o=%.d)",
}

### CODE REVIEW

**Comment by mmicko** [comment]
Expanded dependency rule so we can enforce situations like this : 
		dependency {
			{ "$(OBJDIR)/mame.res" ,  GEN_DIR  .. "/resource/" .. _target .. "vers.rc", true  },
		}

**Comment by bkaradzic** [comment]
How `custombuildtask` is different from `postbuildcommands`?
https://github.com/bkaradzic/genie/blob/master/docs/scripting-reference.md#postbuildcommandscommands

**Comment by mmicko** [comment]
Difference is that tuey depend of input filea. So they are built only if
input changes.

You can edit input file and it will trigger custo build task ans
comiplation of filwa depending on it

**Comment by bkaradzic** [comment]
Can you also update documentation about these features. Include behavior with VS and gmake, where what works.

**Comment by bkaradzic** [comment]
>> I is input file (source file), O is output file (generated file), and those from list of dependencies
>> are 1, 2 and so on

Visual Studio has predefined macros $(OutDir) and such, so you could try to use those instead creating new I/O syntax. Ideally find commonalities between VS and Make and use their naming convention (for input / dependency $(@) $(<), etc.)

**Comment by mmicko** [comment]
Will update documentation, and add more checks for new commands.

Note that dependencies can be used on various ways for when constructing
commands, so there needs to be a way of addressing them.

Will see to clear it out and use gmake like params, but need something like
$(1) $(2) for separate params as well.

Working on implementing this for MAME so it will be a good test case

**Comment by mmicko** [comment]
Documentation and code updated

**Pull request merged**
