### PR TITLE
Add space after filename in 'Generating' message

### PR DESCRIPTION
**Pull request by KageKirin**
Hi,

This PR adds a space between filename and `...` in the `Generating` message.
This makes the filename 'clickable' in iTerm and VSCode, which allows to easily open the generated file.

E.g.
```
Generating ../build/ninja.darwin/release/mydopeassproject.ninja ...
```

Not a big change, but really useful for debugging the generated project files in an editor _without_ having to manually open the file.

Cheers.

### CODE REVIEW

**Comment by bkaradzic** [comment]
Would this work `Generating "../build/ninja.darwin/release/mydopeassproject.ninja"...`?

**Comment by KageKirin** [comment]
Ok, I changed that string to be quoted (lua '%q') and remove the `...`.
It's clickable in this way.

**Comment by bkaradzic** [comment]
Not sure about that absolute path. @rhoot what do you think?

**Comment by KageKirin** [comment]
I'm not sold on the aboslute path either.
In fact, I'm currently another change to print the correct path, relative to cwd.

**Comment by KageKirin** [comment]
Ok, so I removed the absolute path, and put back the relative one.
`Pop cwd after pushing to run file` then restores the original cwd after running `dofile()`.

As a result, embed.lua did not work correctly anymore, `Make paths in embed.lua rely on script dir` fixes the used paths to be correct, i.e. relative to `path.getdirectory(_SCRIPT)`.

I generated bgfx projects with my local modified version, and encountered no further issues.

**Pull request merged**
