### PR TITLE
Added configuration to support user include directories 

### PR DESCRIPTION
**Pull request by jeduden**
xcode-support only. don't have access to the other build systems. :(

### CODE REVIEW

**Comment by bkaradzic** [comment]
Why not just this?

          xcode.printlist(cfg.includedirs, 'HEADER_SEARCH_PATHS')
          xcode.printlist(cfg.userincludedirs, 'HEADER_SEARCH_PATHS')

**Comment by bkaradzic** [comment]
Closed because it's feature that's not supported by other project generators.

**Comment by jeduden** [comment]
The semantics are different. USER_HEADER_SEARCH_PATH are used when an include are specified with quotes instead of angle brackets.

**Comment by bkaradzic** [comment]
There is way to do it with GCC: https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html

**Comment by jeduden** [comment]
Yes. Looks like MS VC doesn't support it. https://msdn.microsoft.com/en-us/library/36k2cdd4.aspx

**Comment by bkaradzic** [comment]
Even if it's not supported by compiler, something should happen with those `userincludedirs`, they should not just ignored if you're not using xcode. They could be for example merged with `includedirs` for VS. For gmake with Clang/GCC there is option `-I-`.

Leaving it hanging like this, would cause all kind of support request when people are using something that works on xcode and just silently fails with other generators.

**Comment by jeduden** [comment]
yes. agreed. i will see if i can work towards this.

**Pull request closed without merging**
