### PR TITLE
support passing the same library to the linker multiple times

### PR DESCRIPTION
**Pull request by h0tw1r3**
When building mame for windows with SDL support, mame depends on the winmm and sdl libraries. Additionally sdl depends on winmm. Rules to link winmm are given twice, but filtered the second time by genie (mergefield). Unfortunately this does not work with gnu ld and static libraries (archives) because the dependencies must be specified in order of reference for each static archive.

The only other option that I know of is to use `--start-group` `--stop-group`, but (according to the manual) "at significant performance cost".

Has the side effect of supporting circular dependencies.

### CODE REVIEW

**Comment by bkaradzic** [comment]
This doesn't look like good fix, just keep throwing lib until it links. It would be better if you count how many times library appears, and then sort them in ascending order based on number of appearances.

I considered `--Wl,--begin/end-group` in the past, but clang's linked didn't have support for it.

**Comment by h0tw1r3** [comment]
A "smart" sort and filter will never work for circular references. Genie is forcing the assumption that it knows more than the software developer - and no way to tell genie, "I really know what I'm doing".
I think Eli explains it very well. http://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking

**Comment by bkaradzic** [comment]
Yeah, but when you have circular dependencies you should make single library to remove circular dependency.

**Comment by h0tw1r3** [comment]
I would normally agree, but In the case of 3rd party libraries for a project that supports multiple architectures (and possibly toolchains), that is simply not practical.

**Comment by bkaradzic** [comment]
I never had this issue with circular dependencies.

**Pull request closed without merging**
