### PR TITLE
Makefile change to responsefiles: 1 entry per line

### PR DESCRIPTION
**Pull request by KageKirin**
Hi,
This is a small change to the gmake responsefile creation to have 1 entry per line, instead of 1 single line having space-separated entries.

Main reason: 1 of my projects has 2000+ source files, and exploded the command line limits when trying to `echo` all the object names into the responsefile (this happended on Mac).

Cheers.

CC: @rhoot for review.

@rhoot: Btw, you were right in the previous PR: there's no need for extra printing the object files/libs going into the responsefile since they'll be printed anyway in verbose mode, and the output is unwanted in silent mode.

### CODE REVIEW

**Comment by bkaradzic** [comment]
> Terminate macro shell calls by semicolon

Why is this needed?

**Comment by KageKirin** [comment]
> > Terminate macro shell calls by semicolon
> 
> Why is this needed?

`$(foreach)` chaining of copy, mkdir etc. macros.
i.e. in the case of having a pre/postbuildcommand iterate over a number files to copy with `$(foreach)`, the code will look like this:

without the added semicolon:
```make
macro = $(SILENT) echo "$(1)"
$(foreach v,$(inputs),$(call macro,$(v));)
``` 

and now with the trailing semicolon in the macro definition:
```make
macro = $(SILENT) echo "$(1)";
$(foreach v,$(inputs),$(call macro,$(v)))
``` 

IMHO, the 2nd one is easier to read and less confusing.
Also, I added the semicolon to have the regular macros be similar to the newly added FPRINT macro, i.e. with trailing semicolon.

I hope this answer is kind of satisfactory. The long story is that I was blocked by the lack of trailing semicolon for a while.

**Comment by KageKirin** [comment]
Thanks for reviewing, and sorry wasting your time with a broken commit.
I just remembered that when I tested it on Windows, I ran make from a bash shell on Windows, not a Windows Command prompt... my bad for not being thourough.

Anyway, I have an idea for a fix that I will implement tomorrow, and then test on Windows (DOS shell and Powershell) as well.
I'll update this PR after testing.

**Comment by KageKirin** [comment]
@rhoot @bkaradzic
Ok, so I fixed the issue and completely changed the PR branch's history.

I also removed 41ab1a1 b/c it did not make any sense after my fixes.

The `FPRINT` macro (daaad72) is now a `$(shell)` call, with the net benefit of being executed once per `$(foreach )` iteration.
And the Windows variant of `FPRINT` consists in `echo.$(1)`, which with $(1) empty results in just an empty line.

Please not that I have a follow up commit already prepared here:
https://github.comKageKirin/GENie/tree/makefile-wholearchive-attfile
If you prefer, I can also close this PR and submit the for the branch above.

**Comment by KageKirin** [comment]
Ok, closing this one in favor just merging both changes with #458 instead.

**Pull request closed without merging**
