### PR TITLE
Make cpp actions: rebuild object files if the makefile changes

### PR DESCRIPTION
**Pull request by phsteven**
For better incremental building. For example, if the compiler flags or linker flags change, make should rebuild everything using those new flags.

### CODE REVIEW

**Comment by mmicko** [comment]
I do understand your use case but it also changed a lot of other behavior. Maybe at least to make this optional.

**Comment by bkaradzic** [comment]
It's not .d files, rather compiler options inside makefile. But one thing that's not clear why makefile need to reference itself. When looking at this change originally I thought makefile will reference master makefile, not itself. It should already work that way, if makefile changed, all dependencies are also invalid. Unless there is some timestamp mismatch.

**Comment by phsteven** [comment]
I also thought make implicitly added a dependency on the makefile for every target, but I was hand-editing a makefile to test new linker flags and it was not the case. I had to delete outputs or add this rule to trigger any rebuild or relink. This is with make from GnuWin32.

If I add option to disable this, I do think it should be on by default. Default should be to capture all dependencies even if it captures too much, rather than miss some dependencies and have builds be incorrect.

Perfect solution would be to have compiler flags and other target parameters defined in a separate file than the targets themselves but that would take a lot more work.

**Comment by bkaradzic** [comment]
I don't like options for things like this. It seems reasonable default, but also I would expect that this is how make should behave too without adding anything. I'm gonna test this more, just to understand what's going on.

**Comment by bkaradzic** [comment]
This is interesting:
https://cr.yp.to/redo/honest-script.html

**Pull request merged**
