### PR TITLE
Add support for 'post gen' callbacks

### PR DESCRIPTION
**Pull request by KageKirin**
Hi again,

this PR adds support for 'post generation' callbacks, i.e. callback functions called immediately after `action.onsolution()`, respectively `action.onproject()`.

User story: I'm generating gradle files per project for Android builds. So far, I'm creating them _before_ the actual project, i.e. inside the project setup, a couple of lines below `project "whatever"`. Using these callbacks allows me to defer the whole creation until the project configuration has been sorted out during the baking phase.

EDIT: The main point of this PR is obviously in combination with the flexible API fields from #459 in such way that custom API fields can be handled in a custom `postsolutioncallback`, respectively in a custom `postprojectcallback`.

Cheers.

### CODE REVIEW

**Comment by KageKirin** [comment]
Note: I guess this one will conflict with #459, so depending on whichever of these 2 PRs gets merged first, I'll update after rebasing.

**Comment by KageKirin** [comment]
Thanks for merging #459 first.
I updated this PR after rebasing to master.

**Comment by bkaradzic** [comment]
Merging this causes:

```
[string "premake.fields = {}..."]:1165: syntax error near ','
```

**Comment by KageKirin** [comment]
Ugh, sorry! I'm facepalming over myself for missing this obvious merge error.

Sorry for trouble. I'll double check my fixes and submit a new PR.

Also, lesson learnt: never do a merge/rebase on a sunday morning.

**Pull request merged**
