### PR TITLE
Fixed for WindowsTargetPlatformVersion not working with non-WinRT apps

### PR DESCRIPTION
**Pull request by IanNorris**
I ran into an issue where a windows desktop app cannot make use of the WindowsTargetPlatformVersion setting. I've updated the project build script to not require the iswinrt setting to be set as this is not actually a requirement. The rest of the check is correct to my knowledge.

### CODE REVIEW

**Comment by bkaradzic** [comment]
I don't know when WindowsTargetPlatformVersion was added to VS, but It looks like this will break VS2010, VS2012, and VS2013 if it wasn't there (my guess it's probably in VS2013 and above).

**Comment by IanNorris** [comment]
I don't have VS2010 still installed to test, but I added this flag to a 2012 and 2013 project and it ignores it as it isn't supported - even with a obviously unsupported value. This change should only mean that non-WinRT projects on VS2015 and above can support having the value set.

**Comment by IanNorris** [comment]
Another option would be to add a check so that it is only added on VS2015, and only if WinRT is set, or if the user explicitly sets it.

**Comment by bkaradzic** [comment]
If it's not causing any issues (not even warning) with VS2012/3 then it's ok as is. I was worried that VS would just barf at unknown xml option.

**Pull request merged**
