### PR TITLE
Fixed OBJDIR create message, removed -L/usr/lib32 and -L/usr/lib64

### PR DESCRIPTION
**Pull request by mmicko**
Fixed OBJDIR create message, previous was causing trouble with -j param, and displaying all created folders make much more sense

### CODE REVIEW

**Comment by mmicko** [comment]
Reason is getting message 
ld: warning: directory not found for option '-L/usr/lib32'

**Comment by bkaradzic** [comment]
I was thinking of removing completely /usr/lib[32/64]...

**Comment by mmicko** [comment]
Sure that is fine too

On Mon, Mar 30, 2015 at 5:38 PM, Branimir Karadžić <notifications@github.com

**Comment by mmicko** [comment]
Done :)

**Pull request merged**
