### PR TITLE
Making libs/executable not re-link all the time

### PR DESCRIPTION
**Pull request by mmicko**
When $(TARGETDIR) is in dependency list it makes all files to be relinked on each make, this patch removes that

### CODE REVIEW

**Comment by bkaradzic** [comment]
That's correct behavior, it doesn't relink, make just executes dependency check for all projects. With your change if you change library, it will fail to compile and link it, and your executable will pick stale library.

**Comment by mmicko** [comment]
Will check linux since on windows I get this strange behavior or re-linking
all libraries.

On Thu, Oct 15, 2015 at 6:29 PM, Branimir Karadžić <notifications@github.com

**Comment by ajohnson23** [comment]
First off I'm speaking only for linux right now. I'm not sure on windows.
This "always re-linking" problem can come up if you're sharing a single TARGETDIR for more than one target (e.g. a static lib and a main executable that depends upon it).
cmftStudio actually does this, so you may be able to clone it and do make linux-debug64 a couple times in a row and the second time observe that it relinks all library targets and the executable target. 
When I ran "make -d linux-debug64" the second time, I noticed lines like this:
```
Prerequisite `../../_build/linux64_gcc/bin' is newer than target `../../_build/linux64_gcc/bin/libbgfxDebug.a'.

Shortly followed by:
 Must remake target `../../_build/linux64_gcc/bin/libbgfxDebug.a'.
```
Hopefully you can repro as well. I think when running make, first the static libs build, which updates the TARGETDIR timestamp. The executable builds immediately afterward, which again updates the TARGETDIR timestamp. The TARGETDIR timestamp is now newer than the timestamp of the static lib files. This always triggers a re-link of the static libs the next time you build since it thinks they're stale, which also of course ends up causing the exe to relink. 
@bkaradzic, what did you mean by "if you change library, it will fail to compile and link it, and your executable will pick stale library."?
With cmftStudio as the example, as far as I can see, if I update bgfx (e.g. "touch bgfx/src/renderer_gl.cpp"),  then "make linux-debug64" in cmftStudio, the build picks up those library changes fine and relinks bgfx and cmftStudio, even with [these changes to genie](https://github.com/ajohnson23/genie/commit/6e5b28442c69884b10b3250bd62f8eb4e934af78) in place. I can send that as a merge request if you want -- similar to changes by @mmicko, but leaves $TARGETDIR in as an order-only dependency so that mkdir still gets run.

**Comment by bkaradzic** [comment]
Interesting didn't know you can use `|` as dependency. If it works as expected you can make PR.

**Comment by mmicko** [comment]
I can just confirm that this change works fine on Windows, just tested it.

**Comment by mmicko** [comment]
Actually  if you do build, and first make after that will regenerate all
libs, but one after that will be fine.
So still not good enough, unfortunately.

**Comment by ajohnson23** [comment]
@mmicko That regenerate all problem is on windows, correct? I'll take a look.

**Pull request closed without merging**
