### PR TITLE
Added linkoptions_late function

### PR DESCRIPTION
**Pull request by codecat**
This adds a `linkoptions_late` function to resolve the issue mentioned in #416.

Probably need to add some info about this function to the documentation as well, but I'm submitting this PR anyway for review.

### CODE REVIEW

**Comment by bkaradzic** [comment]
Link order for GCC might cause issues, but generally it's fixable without any changes.

I don't like that this is only Makefile fix. Workaround in your issue seems better because it would fix other build scripts too.

Adding @rhoot to see this, since I know he did some link order stuff on one project.

**Comment by codecat** [comment]
I agree, the workaround is indeed better. However, in my case, I wasn't able to actually use that workaround because I'm generating the GENie scripts on a different system configuration than where I'm actually running the final makefiles. (Some background: I'm running the build in the Steam Runtime.)

It's probably better to just run GENie inside of the runtime as well so that my workaround from the issue works, but our scripts have some things that rely on it being built outside of the runtime, unfortunately.

**Comment by rhoot** [comment]
So I see the problem, but wouldn’t a better solution be to modify `premake.gcc.getlinkflags` to preserve the backticks instead of falling into the else case and prefixing with `-l`? Then you could just use ``links {“`wx-config --libs`”}`` instead of using `linkoptions`.

**Comment by codecat** [comment]
That would make a lot of sense. I can modify this PR to be that probably tomorrow.

**Pull request closed without merging**
