### PR TITLE
Allow static-libs to have link dependencies

### PR DESCRIPTION
**Pull request by Muzza**
In VS, static libs can have link dependencies just like exe's do.

### CODE REVIEW

**Comment by bkaradzic** [comment]
Please flatten your changes. Too many commits and merges.

**Comment by Muzza** [comment]
Well I tried, but I can't get rebase to work even though it really should be a trivial operation and I've now got so many other additions lined up that its becoming painful to integrate one change at a time. Wasted hours on this, so I'm giving up for now :(

**Comment by bkaradzic** [comment]
It's really hard to understand what's going on in these changes, things got added/removed that should be in.

It seems this is the only relevant change (by your PR description):
https://github.com/bkaradzic/GENie/pull/165/commits/25f4577066ba67f616dda688fe1d789a6459ba91

**Comment by Muzza** [comment]
Yes, there are only 3 small changes in 1 file (vs2010_vcxproj.lua) that are relevant. 
The problem is that I made this branch a week ago with the feature, and I've had to merge in your changes back in to my branch at various times. All those commits make it look messy when in reality it's a tiny change.

As I understand git, I should be able to rebase to get rid of all those useless commits so you only see the one that is relevant, but like I say, I can't get rebase to work.

**Comment by bkaradzic** [comment]
You can do something like this, clone GENie again. Copy files you changed for this commit. Do `git add -p` select which hunks you want to add, commit only relevant changes, submit PR.

**Comment by Muzza** [comment]
I ended up restarting my master from upstream (had to google to do this), making a local copy of my changes. Creating a new branch from the new master. Manually copying across the changes using WinMerge. Then committing it. All for a 9 line trivial change.

**Comment by bkaradzic** [comment]
`git add -p` is like winmerge thing, just shows you hunks and you choose with y/n which ones you want staged.

**Pull request closed without merging**
