### PR TITLE
Adding option to exclude files from Precompiled Header + some extra flags

### PR DESCRIPTION
**Pull request by Muzza**
Adds **nopch** option that allows specified files within a project to not use the precompiled header. This is useful when mixing C and C++ files in a project.
e.g. `nopch { "a_file.c" }`

Also adds some new compile flags:
**MinimumWarnings**  - Sets compiler warning level to 1
**NoBufferSecurityCheck** - Turns off Visual Studio 'Security Check' option. Can give up to 10% performance improvement.
**NoWinRT** - Disables Windows RunTime Extension for project. Useful if mixing WinRT and non-WinRT projects together in a solution.
**NoWinMD**- Disables Generation of Windows Metadata in WinRT projects.
**WholeProgramOptimization** - enables this option in Visual Studio.

This is my first attempt at doing GitHub pull requests, so apologies in advance if I've done something wrong!

### CODE REVIEW

**Comment by bkaradzic** [comment]
Can you split these into individual PR? Too many different features getting added at once.

**Comment by bkaradzic** [comment]
Like PR#1 NoBufferSecurityCheck, PR#2 WholeProgramOptimization, PR#4 WinRT stuff

**Comment by bkaradzic** [comment]
Btw, you need `nopch` for WinRT CX files, or something else? If you rename CX files to .cx it will be done automatically.

**Comment by Muzza** [comment]
I'll look to split them up. I need nopch for other purposes - I have libs that have 95% cpp files using a PCH and a few extra C files that come from 3rd Parties that don't work with the PCH, so need it disabled.

**Comment by bkaradzic** [comment]
If this is true always for .c files, then instead adding nopch, it would be better to add `function path.isSourceFileUsingPCH(fname)` and then apply those settings automatically (I did this for WinRT .cx files).

**Comment by bkaradzic** [comment]
Anyhow I your commits contain `script.c` so it causes merge conflict.

**Comment by Muzza** [comment]
nopch is not only useful for .c files. I use it if a project integrates a few 3rd party c++ files as well (which are not compatible with the precompiled header used by everything else in the project)

**Pull request closed without merging**
