### PR TITLE
When merging two lists, maintain relative order of items.

### PR DESCRIPTION
**Pull request by beevik**
With some linkers, such as ld, the order in which libraries are
included is important. This change ensures that the relative
order of libraries does not change as multiple "links"
configurations are merged.

The side effect is that all configuration lists will be merged this
way (including, for example, library and include directories). But
order should not matter with these other types of lists.

### CODE REVIEW

**Comment by zao** [comment]
I wonder a bit about the wording around order of include/library directories not mattering.
Unless this is something particular to GENie guts (only one set of dirs or something), the order of directories matters greatly when it comes to resolving includes and linking libraries that exist in more than one place.

**Comment by beevik** [comment]
that's a really good point, @zao. I think I'll need to find a way to have this change apply only to the libs.

**Comment by bkaradzic** [comment]
It seems that in case of directories it's expected for files to have unique names, and if files with the same name exist in multiple include/lib directories which one will be picked is undefined.

**Comment by beevik** [comment]
I can imagine a scenario where reordering the directories could create a problem.  This commit could lead to an undesirable reordering.

**Comment by beevik** [comment]
I submitted another pull request that applies reordering only to libs.
https://github.com/beevik/GENie/commit/3233ca96fe73a8133b58339b493063b53dfa1cca

**Pull request merged**
