### PR TITLE
Add vs2019 support

### LINKED ISSUE #405: Add build support for vs2019
The VS 2019 preview snapshot 2 has been released. It would be good to add a vs2019 flag :)

### PR DESCRIPTION
**Pull request by htmlboss**
WIP.

Resolves #405 

Am I missing anything??

### CODE REVIEW

**Comment by bkaradzic** [comment]
Don't have VS2019 installed... I can wait until you have complete PR.

**Comment by kazblox** [comment]
Are you refraining from using the current toolset and the latest solution version? There were some heavy changes for the v142/Current such as features having to deal with fields such as "CreateManifestResourceNames" and "CoreCompile"; not sure what exactly was changed, but.....

**Comment by bkaradzic** [comment]
> Are you refraining from using the current toolset and the latest solution version?

No, I just want PR that would just work since I didn't install VS2019 yet, so I can't troubleshoot issues.

VS2019 should be supported to full extent, just need someone who has time to do it properly, or I'll do it once I install it.

**Comment by kazblox** [comment]
I'm talking to htmlboss, who made the PR. But anyways....

**Pull request closed without merging**
