### PR TITLE
Adding support for per-config files to XCode.

### PR DESCRIPTION
**Pull request by rhoot**
Same as #208 but for XCode projects.

Also adding support for assembly files while I'm at it.

### CODE REVIEW

**Comment by bkaradzic** [comment]
There is issue when using exclude:

[string "premake.xcode.parameters = { }..."]:604: '../../../src/amalgamated.cpp' would be excluded by the rule to exclude 'amalgamated.cpp'
stack traceback:
        [C]: in function 'error'
        [string "premake.xcode.parameters = { }..."]:604: in local 'verify_file'
        [string "premake.xcode.parameters = { }..."]:614: in upvalue 'cfg_excluded_files'
        [string "premake.xcode.parameters = { }..."]:646: in field 'XCBuildConfiguration_Project'
        [string "premake.xcode.parameters = { }..."]:735: in field 'XCBuildConfiguration'
        [string "local xcode = premake.xcode..."]:110: in local 'callback'
        [string "premake._filelevelconfig = false..."]:5: in field 'generate'
        [string "premake.xcode = { }..."]:66: in field 'onproject'
        [string "premake.action = { }..."]:23: in field 'call'
        [string "_WORKING_DIR        = os.getcwd()..."]:82: in function '_premake_main'
make: *** [projgen] Error 1

**Comment by rhoot** [comment]
Yeah, if you look at the line generating the error you'll see:

```
-- xcode only allows us to exclude files based on filename, not path...
error("'" .. file .. "' would be excluded by the rule to exclude '" .. name .. "'")
```

From what I can tell, the xcode project generation previously only supported `excludes` on a project level, not per configuration (see xcode_common.lua:709). I added support for it with this change, but the only way XCode supports for excluding a file per-configuration rather than per-project is through only the filename, disregarding paths.

**Comment by rhoot** [comment]
Basically that error is telling you that you're excluding a file with the same name as a file that should *not* be excluded. It should work if you exclude it from the project, but it won't work for xcode if you try to exclude it only from a certain configuration.

**Comment by bkaradzic** [comment]
It's this block of code: https://github.com/bkaradzic/bgfx/blob/master/scripts/bgfx.lua#L131

Only thing there might be amaglamated.cpp that gets included and then excluded?

**Pull request merged**
