### PR TITLE
Add Cpp* standard flags

### PR DESCRIPTION
**Pull request by hugoam**
This adds a couple of flags to specify which c++ standard above c++03 your projects need to use : 
Cpp11, Cpp14, Cpp17, CppLatest
(CppLatest is useful if you're developping an experimental project on the c++ cutting edge, for now it maps to c++2a in gcc based, and c++latest in visual studio)

Using these flags can be used to simplify the toolchain (it's littered with a number of "-std=c++11" lines).
I find them very useful and I'd like to not maintain my own GENie fork so let me know if you think this is a welcome addition to GENie.

The only tools I use that need to specify the standard are gcc and vs2017 (lower versions of VS don't have a way to specify the standard I reckon) so I added this two. Let me know if some are missing ?

### CODE REVIEW

**Comment by bkaradzic** [comment]
This doesn't work correctly when there are with C files in the project. Follow buildoptions_cpp how to properly implement it. Also this option should be set for for ObjC++.

**Comment by bkaradzic** [comment]
Btw, you can test this with bgfx. Remove "-std=c++11" from bx/scripts/toolchain.lua and add Flags { Cpp11 }

**Comment by hugoam** [comment]
For gcc : I made a mistake when sorting my branches and put it in `cflags` instead of `cxxflags`, let me fix it right away.
For Visual Studio 2017 : it's a VS project wide setting so I suppose VS handles it correctly ? Let me check and redo the pull-request. The flags don't do anything for VS < 2017.

**Comment by hugoam** [comment]
image
Here is a screenshot in VS2017, this is the properties for a C file, the c++ standard is set but it doesn't seem to prevent it to compile properly ?

**Comment by bkaradzic** [comment]
I meant for GCC...
https://github.com/bkaradzic/GENie/blob/2f221f510430150ba67476fc4bba2f9f0e072190/src/tools/gcc.lua#L26

It should go to `cxxflags` and `objcxxflags` instead.

**Pull request merged**
