### PR TITLE
Adds NoWinMD option

### PR DESCRIPTION
**Pull request by Muzza**
**NoWinMD** - Disables Generation of Windows Metadata in WinRT projects

Now without scripts.c

### CODE REVIEW

**Comment by Muzza** [comment]
I'm new to using git, but I'm guessing this has failed because the NoWinMD change was right next to the NoWinRT change and as soon as you merged one, git would fail to merge the other.
So the only way I could get this through is by either:
1. Submitting them together (but you asked me not to)
2. Only submitting one commit at a time, and waiting for you to merge one before working on the next.

Is this correct or am I just using git completely wrong?

**Comment by bkaradzic** [comment]
You could do branch for each change, and then submit it all individually. Start from same clean state, add feature, move to next feature without previous changes. Also one-by-one would work too if that's simpler. It all depends on preferred workflow.

**Comment by Muzza** [comment]
That's exactly what I did. I had a clean branch from each change, identical to your master. On each branch I added just one new feature.
Any one of my commits could be merged without conflict, but as soon as you merge one, the others become invalid.

**Comment by bkaradzic** [comment]
I never had this happen... But I also never had more than three different changes, actually I often have two changes like this on different branches, and merge always works without any problems.

**Comment by Muzza** [comment]
After having merged back from the master to my branch, I see the problem is simply that the NoWinRT and NoWinMD flags are adjacent to each other, meaning that as soon as one is committed to master, the other causes a conflict and needs merging.
So yes, the only solution is for me to submit them together, or wait for you to integrate one, then merge it back to my branch and then submit the next.
I'm used to perforce where this kind of simply merge is trivial, but I'm starting to get the hang of git now.

**Comment by bkaradzic** [comment]
Yeah, for trivial things like NoWinRT/MD is fine together. Anyhow you can submit it again.

**Pull request closed without merging**
