### PR TITLE
Put back the code to enable file-level configuration as it is useful …

### PR DESCRIPTION
**Pull request by bradhugh**
…for source file specific configuration properties.

### CODE REVIEW

**Comment by bkaradzic** [comment]
Testing this, it's actually huge slowdown for large project...

**Comment by bradhugh** [comment]
What kind of slow down are you seeing? I'd like to try to Repro. If it can't be rectified, Maybe we can provide a global switch to enable it.

**Comment by bkaradzic** [comment]
I added profiler... You can run it with `--debug-profiler`. This is what I see:

```
------------------- L:iskeywordsmatch@@d:/genie/src/base/bake.lua:96 -------------------
Sample count:         54337
Time spend total:       342.315s
Time spent in children: 298.877s
Time spent in self:     43.438s
Time spent per sample:  0.00630s/sample
Time spent in self per sample: 0.00080s/sample

Child L:iskeywordmatch@@d:/genie/src/base/bake.lua:71 sampled  47434 times. Took 298.88s

------------------- L:startswith@@d:\genie\src\/base/string.lua:48 -------------------
Sample count:         4208
Time spend total:       26.455s
Time spent in children: 0.000s
Time spent in self:     26.455s
Time spent per sample:  0.00629s/sample
Time spent in self per sample: 0.00629s/sample

------------------- L:postprocess@@d:/genie/src/base/bake.lua:683 -------------------
Sample count:         57596
Time spend total:       362.450s
Time spent in children: 343.465s
Time spent in self:     18.985s
Time spent per sample:  0.00629s/sample
Time spent in self per sample: 0.00033s/sample

Child L:iskeywordsmatch@@d:/genie/src/base/bake.lua:96 sampled  54126 times. Took 341.31s
Child L:icontains@@d:\genie\src\/base/table.lua:19 sampled    435 times. Took 2.15s
```

**Comment by bkaradzic** [comment]
Also added this check:
https://github.com/bkaradzic/GENie/blob/master/src/base/bake.lua#L732

**Comment by bradhugh** [comment]
Ooh, this won't work since the other feature for C++ deployment content is not for .NET projects.  I'll be happy to take a look at optimizations.  I'd rather have a global opt-in switch for now if that's possible.  I'll work on a global switch (off by default) and send a pull.

**Comment by bradhugh** [comment]
Oh, and I will definitely run profiler to see if we can optimize.  Question, which project were you generating?  Is it somewhere on GitHub where I could try it also?

**Comment by bkaradzic** [comment]
For some reason when profiler is used in release build function name and function body is mangled together. Just use debug build for profiling for now.

**Pull request merged**
