### PR TITLE
Added premake.make.linkoptions_after flag

### PR DESCRIPTION
**Pull request by mmicko**
Added premake.make.linkoptions_after flag to be able to place link options after libs in link commands, default is false as it was before

### CODE REVIEW

**Comment by bkaradzic** [comment]
Do you have problem with link order?

**Comment by mmicko** [comment]
Yes, and parameters are in some cases taken in linkoptions since they are
 pkg-config  outputs, that keeps it in that format.

My idea is to make option to define static libraries dependencies so we can
sort them in proper order. But this helps for now

**Comment by bkaradzic** [comment]
I just had similar issue and I was fixing it without changes to GENie. Basically you should fix dependencies in your script.

Only change I wanted to make was to add --start-group <libs> --end-group, but that option is unsupported by LLVM linker. If you have idea how to get this on LLVM that would be the best fix.

**Comment by mmicko** [comment]
Ok will work towards that then

**Pull request closed without merging**
