### PR TITLE
Added support for per-configuration excludes in visual studio(2010+)

### PR DESCRIPTION
**Pull request by teddemunnik**
This pull request adds support for the `excludes` command in configurations. I am using this personally to exclude some development-only source files from release builds.

Example usage:
```lua
files{		
	"src/**.cpp",
	"src/**.h",
	"include/**.h"
}
configuration { "Release" }
excludes{
	"src/importing/**.cpp"
}
```

### CODE REVIEW

**Comment by neilogd** [comment]
Will this also work for gmake & xcode builds?

**Comment by teddemunnik** [comment]
@neilogd  I did do some quick research to make sure it is also possible to implement in those targets, but unfortunately it is not implemented in this pull request as I currently neither have experience with those targets nor access to a mac.

**Comment by neilogd** [comment]
If that's the case perhaps we need to get an issue submitted if this pull
request is taken? Just so that it doesn't get forgotten about and introduce
inconsistencies between builds :) I think the feature is a good idea, just
needs to be uniform across all build targets.

**Comment by teddemunnik** [comment]
I totally agree! Perhaps a branch could be set up where features sit until they are implemented for all relevant targets too? It would be a shame if implementing a feature would always mean the same person having to implement it for each target, while other (potential) collaborators would be better suited for the job.

**Comment by neilogd** [comment]
A branch sounds good to me, the call on this lies with Branimir mind :) I
can deal with gmake stuff since that's primarily the target I use, but
someone else would need to handle xcode. For features that cover all
targets a process for it would be pretty useful.

**Comment by bkaradzic** [comment]
What would be the best way to do this branch? Maybe simplest right now is just to work in Ted's repo until we at least have vs+gmake and then merging it into main?

**Comment by bkaradzic** [comment]
I'm also fine with accepting this if gmake is going to be added in couple-of-weeks timeframe.

**Comment by teddemunnik** [comment]
I was thinking the development / master kind of setup that a lot of repositories tend to use. However I am also fine with your alternatives, depending on the timeframe in which @neilogd can do a gmake port.

**Comment by neilogd** [comment]
I'm in the process of moving house, but realistically it doesn't sound like
a particularly difficult task. I could probably take a look at it tonight?

I like the idea of a development branch, it at least gives a staging area
for things like this before hitting master.

**Comment by bkaradzic** [comment]
We'll do it live! :)

**Comment by neilogd** [comment]
http://cdn.meme.am/instances/500x/52615776.jpg

**Comment by bkaradzic** [comment]
@neilogd Exactly! :)

**Comment by neilogd** [comment]
Pushed a change for this here: https://github.com/bkaradzic/genie/commit/bb7b4651a464649012f5681db9f6cb4d2db9986a

Thought best to not commit to master immediately. Let me know if there are any issues with it!

**Comment by bkaradzic** [comment]
I just started using this, and I think it would be better if we make split `excludes` into `excludes` and `removefiles`. `removefiles` would behave as `excludes` in general all configuration case, and `excludes` would always add file to solution but disable it for selected configurations (or all configurations if it's declared in all configurations).

**Comment by neilogd** [comment]
So removefiles to remove entirely, so be global, not config specific, and
have excludes as a config specific thing?

**Comment by bkaradzic** [comment]
Yeah `removefiles` removes them from solution regardless of configuration. `excludes` would still add files into solution but would disable build like it does when configuration is specified.

**Comment by neilogd** [comment]
That seems like a great idea to me then :)

**Comment by teddemunnik** [comment]
Sounds good to me too, very consistent with the rest of the API. Looks like this won't break existing projects either which is great!

**Pull request merged**
