### PR TITLE
Disambiguate prebuildcommand target names in Ninja

### PR DESCRIPTION
**Pull request by Dentoid**
Prebuild commands used a common "__prebuildcommands" target name in Ninja build files. This resulted in target name collisions, which this PR fixes.

### CODE REVIEW

**Comment by bkaradzic** [comment]
I can't find `__prebuildcommands` in Ninja repo/docs.

**Comment by Dentoid** [comment]
`__prebuildcommands` is not a Ninja concept, but a special target used as a way of supporting GENie's `prebuildcommands` in Ninja. Basically it's a target that's added as a dependency to all other targets in a project to make sure it's built first (added by me in a PR a long time ago).

The target was generated for every project using `prebuildcommands`, and if there were multiple projects doing so the `__prebuildcommands `targets would collide.

**Comment by bkaradzic** [comment]
Ok but how adding extra `_` would fix this issue? Wouldn't you have exactly the same issue later when `__prebuildcommands_` becomes common?

**Comment by Dentoid** [comment]
The extra _ is irrelevant, adding the project name as suffix is the important part.

**Pull request merged**
