### PR TITLE
XCode updates

### PR DESCRIPTION
**Pull request by rhoot**
Some early spring cleaning and general updates to the XCode actions.

- Restructured the xcode folder to look more like the vstudio folder.
- Removed the xcode3 action.
- Removed the xcode6 code, since it didn't have an action associated with it anyway.
- Added xcode8 and xcode9 actions, that base their settings on xcode4.
- Fixing uuid collisions that were causing issues in XCode (before these changes).

### CODE REVIEW

**Comment by rhoot** [comment]
Actually, let me update the docs too.

**Comment by rhoot** [comment]
Turns out actions aren't documented anywhere, so I just added it to the readme.

**Comment by bkaradzic** [comment]
You left some printfs, and generating VS project is spamming stdout...

**Comment by bkaradzic** [comment]
Nevermind, can you resubmit this PR again?

**Pull request merged**
